# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2b48fef6375e3326f6bfe72873366f6425658c64c833b7a7864dae6ea5bb4842086e8f0187a6909eb528701b326b4f6b165e3f1dd1e2052da99c0c06544926e

test:
  secret_key_base: a32bb63e25198939d5400036e965009f61e579cce5d61ae8be615145bbf48967af6703486792ad7ea4514eef19061879dda3311e481836fbdef489224ae07f36

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
